# Importación de librerías

In [44]:
import pandas as pd

# Ingesta de datos

## Insumos

In [45]:
insumos = pd.read_excel("data\INSUMOS OPERACIONALES STOCK RELIX.xlsx", sheet_name='Insumos Operacionales 2025', skiprows=7)

In [46]:
insumos.head()

,Unnamed: 0,ITEM,CODIGO SAP/OTRO,DESCRIPCION DEL MATERIAL,CLASIFICACIÓN,U M,OBSERVACIONES,Unnamed: 7
0,NaN,1.1,11174821,DUCTO RECTO;PE100;PN20;280 MM;12 M;PL,PIPING,UN,NaN,NaN
1,NaN,1.2,11177716,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL - 8"" diam",PIPING,UN,NaN,NaN
2,NaN,1.3,en catalogacion,"Tuberia HDPE 200MM DN, Flanges Moviles C150, c...",PIPING,UN,NaN,NaN
3,NaN,1.4,11151921,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL - 8"" diam ...",PIPING,UN,NaN,NaN
4,NaN,1.5,11019704,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL",PIPING,UN,NaN,NaN

In [47]:
insumos = insumos.drop(insumos.columns[[0, 7]], axis=1)
insumos.head()

,ITEM,CODIGO SAP/OTRO,DESCRIPCION DEL MATERIAL,CLASIFICACIÓN,U M,OBSERVACIONES
0,1.1,11174821,DUCTO RECTO;PE100;PN20;280 MM;12 M;PL,PIPING,UN,NaN
1,1.2,11177716,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL - 8"" diam",PIPING,UN,NaN
2,1.3,en catalogacion,"Tuberia HDPE 200MM DN, Flanges Moviles C150, c...",PIPING,UN,NaN
3,1.4,11151921,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL - 8"" diam ...",PIPING,UN,NaN
4,1.5,11019704,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL",PIPING,UN,NaN

In [48]:
insumos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 491 entries, 0 to 490
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ITEM                       490 non-null    float64
 1   CODIGO SAP/OTRO            490 non-null    object
 2   DESCRIPCION DEL MATERIAL   490 non-null    object
 3   CLASIFICACIÓN              490 non-null    object
 4   U M                        486 non-null    object
 5   OBSERVACIONES              0 non-null      float64
dtypes: float64(2), object(4)
memory usage: 23.1+ KB

In [49]:
insumos.columns

Index(['ITEM', 'CODIGO SAP/OTRO', 'DESCRIPCION DEL MATERIAL ',
       'CLASIFICACIÓN ', 'U M', 'OBSERVACIONES'],
      dtype='object')

In [50]:
insumos.columns = insumos.columns.str.strip()

In [51]:
insumos[insumos['CLASIFICACIÓN'].isnull()]
# TODO: llenar clasificación NaN

,ITEM,CODIGO SAP/OTRO,DESCRIPCION DEL MATERIAL,CLASIFICACIÓN,U M,OBSERVACIONES
481,11.29,11220592,MAURO TUERCA STORZ 4 PULGADAS LINEA DE RIEGO,NaN,UN,NaN

In [52]:
insumos['CLASIFICACIÓN'].unique()

array(['PIPING ', 'PIEZAS ESPECIALES', 'VALVULAS', 'HUMECTACIÓN ',
       'PIEZÓMETROS ', 'IMPERMEABILIAZACIÓN ', 'OBRAS CIVILES ',
       'SERVICIOS GENERALES', 'ILUMINACION EMPALIZADA', 'TALLER BERLIAM',
       nan, 'RIEGO MURO TRANQUE', 'INSTRUMENTACIÓN GEOTECNICA'],
      dtype=object)

In [68]:
insumos['CLASIFICACIÓN'] = insumos['CLASIFICACIÓN'].str.strip()
insumos['CLASIFICACIÓN'].unique()

array(['PIPING', 'PIEZAS ESPECIALES', 'VALVULAS', 'HUMECTACIÓN',
       'PIEZÓMETROS', 'IMPERMEABILIAZACIÓN', 'OBRAS CIVILES',
       'SERVICIOS GENERALES', 'ILUMINACION EMPALIZADA', 'TALLER BERLIAM',
       nan, 'RIEGO MURO TRANQUE', 'INSTRUMENTACIÓN GEOTECNICA'],
      dtype=object)

In [54]:
insumos[insumos['CODIGO SAP/OTRO'].isnull()]
# TODO: Considerar iluminación empalizada como categoría?

,ITEM,CODIGO SAP/OTRO,DESCRIPCION DEL MATERIAL,CLASIFICACIÓN,U M,OBSERVACIONES
490,NaN,NaN,NaN,ILUMINACION EMPALIZADA,NaN,NaN

In [55]:
insumos[insumos['U M'].isnull()]

,ITEM,CODIGO SAP/OTRO,DESCRIPCION DEL MATERIAL,CLASIFICACIÓN,U M,OBSERVACIONES
166,4.40,catalogar sap,"Flange Ciego diam 28"" ANSI C150",PIEZAS ESPECIALES,NaN,NaN
167,4.50,catalogar sap,"Flange Ciego 28"" ANSI C300",PIEZAS ESPECIALES,NaN,NaN
348,9.95,catalogar sap,Tubos PVC Bastones Reflectantes,SERVICIOS GENERALES,NaN,NaN
352,9.99,11215216,BOQUILLAS DEPOSITACION 50MM POLIURETANO,SERVICIOS GENERALES,NaN,NaN
490,NaN,NaN,NaN,ILUMINACION EMPALIZADA,NaN,NaN

In [56]:
insumos['U M'].unique()
# TODO: Corregir UM inconsistentes

array(['UN', nan, 'kit', 'Bins', 'M2', 'ROLLOS', 'M3', 'M', 'kg', 'Mt',
       'Kg', 'Metros', 'KIT', 'lts', 'mt', 'Unidad', 'Bin', 'Rollo',
       'saco 25 kg', 'Kit'], dtype=object)

In [69]:
insumos.head(3)

,ITEM,CODIGO SAP/OTRO,DESCRIPCION DEL MATERIAL,CLASIFICACIÓN,U M,OBSERVACIONES
0,1.1,11174821,DUCTO RECTO;PE100;PN20;280 MM;12 M;PL,PIPING,UN,NaN
1,1.2,11177716,"DUCTO;HDPE;12MT;PE100;PN12,5;F01;PL - 8"" diam",PIPING,UN,NaN
2,1.3,en catalogacion,"Tuberia HDPE 200MM DN, Flanges Moviles C150, c...",PIPING,UN,NaN

In [70]:
insumos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 491 entries, 0 to 490
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ITEM                      490 non-null    float64
 1   CODIGO SAP/OTRO           490 non-null    object
 2   DESCRIPCION DEL MATERIAL  490 non-null    object
 3   CLASIFICACIÓN             490 non-null    object
 4   U M                       486 non-null    object
 5   OBSERVACIONES             0 non-null      float64
dtypes: float64(2), object(4)
memory usage: 23.1+ KB

## Ingresos

In [57]:
ingresos = pd.read_excel("data\INSUMOS OPERACIONALES STOCK RELIX.xlsx", sheet_name='INGRESO', skiprows=9)

In [58]:
ingresos.head()

,Unnamed: 0,CLASIFICIACIÓN,CÓDIGO SAP/OTRO,DESCRIPCIÓN DEL MATERIAL,UNIDAD,CANTIDAD,FECHA DE INGRESO,RESERVA,GUIA DESPACHO,OC,USO: OPERCIONES / PROYECTO,RECIBIDO POR:,UBICACIÓN,EMPRESA,PRECIO UNITARIO,TOTAL NETO,OBSERVACIONES
0,NaN,VALVULAS,11178702,"Valvula 8""clase 300 (L)\nVÁLVULA;FLSMIDTH;TGHP...",UN,8.0,2025-09-25,5080832,135973,4510237047,EMPALIZADA 23,KAREM GONZALEZ,PATIO EX COSAPIN,FLSMIDTH S.A,11035478.0,88283824.0,NaN
1,NaN,VALVULAS,11117559,"Válvula Cuchillo 8"" FL (c 150)\nVALVULA CUCHI...",UN,20.0,2025-09-25,4947998,135974,4510231212,OPERACIONES,KAREM GONZALEZ,PATIO EX COSAPIN,FLSMIDTH S.A,2783917.0,55678340.0,NaN
2,NaN,IMPERMEABILIAZACIÓN,11019930,GEOMEMBRANA;7.01X210MT 1.5MM ESP HDPE,M2,2944.0,2025-09-28,5152005,151237,4510240486,OPERACIONES,KAREM GONZALEZ,PATIO EX COSAPIN,POLYTEX S.A,2173.0,6397312.0,NaN
3,NaN,IMPERMEABILIAZACIÓN,11019930,GEOMEMBRANA;7.01X210MT 1.5MM ESP HDPE,M2,2944.0,2025-09-28,5152005,151157,4510240486,OPERACIONES,KAREM GONZALEZ,PATIO EX COSAPIN,POLYTEX S.A,2169.0,6385536.0,NaN
4,NaN,IMPERMEABILIAZACIÓN,11019930,GEOMEMBRANA;7.01X210MT 1.5MM ESP HDPE,M2,2944.0,2025-09-28,5152005,151017,4510240486,OPERACIONES,KAREM GONZALEZ,PATIO EX COSAPIN,POLYTEX S.A,2205.0,6491520.0,NaN

In [59]:
ingresos = ingresos.drop(ingresos.columns[0], axis=1)
ingresos.head()

,CLASIFICIACIÓN,CÓDIGO SAP/OTRO,DESCRIPCIÓN DEL MATERIAL,UNIDAD,CANTIDAD,FECHA DE INGRESO,RESERVA,GUIA DESPACHO,OC,USO: OPERCIONES / PROYECTO,RECIBIDO POR:,UBICACIÓN,EMPRESA,PRECIO UNITARIO,TOTAL NETO,OBSERVACIONES
0,VALVULAS,11178702,"Valvula 8""clase 300 (L)\nVÁLVULA;FLSMIDTH;TGHP...",UN,8.0,2025-09-25,5080832,135973,4510237047,EMPALIZADA 23,KAREM GONZALEZ,PATIO EX COSAPIN,FLSMIDTH S.A,11035478.0,88283824.0,NaN
1,VALVULAS,11117559,"Válvula Cuchillo 8"" FL (c 150)\nVALVULA CUCHI...",UN,20.0,2025-09-25,4947998,135974,4510231212,OPERACIONES,KAREM GONZALEZ,PATIO EX COSAPIN,FLSMIDTH S.A,2783917.0,55678340.0,NaN
2,IMPERMEABILIAZACIÓN,11019930,GEOMEMBRANA;7.01X210MT 1.5MM ESP HDPE,M2,2944.0,2025-09-28,5152005,151237,4510240486,OPERACIONES,KAREM GONZALEZ,PATIO EX COSAPIN,POLYTEX S.A,2173.0,6397312.0,NaN
3,IMPERMEABILIAZACIÓN,11019930,GEOMEMBRANA;7.01X210MT 1.5MM ESP HDPE,M2,2944.0,2025-09-28,5152005,151157,4510240486,OPERACIONES,KAREM GONZALEZ,PATIO EX COSAPIN,POLYTEX S.A,2169.0,6385536.0,NaN
4,IMPERMEABILIAZACIÓN,11019930,GEOMEMBRANA;7.01X210MT 1.5MM ESP HDPE,M2,2944.0,2025-09-28,5152005,151017,4510240486,OPERACIONES,KAREM GONZALEZ,PATIO EX COSAPIN,POLYTEX S.A,2205.0,6491520.0,NaN

In [71]:
ingresos.columns

Index(['CLASIFICIACIÓN ', 'CÓDIGO         SAP/OTRO',
       'DESCRIPCIÓN DEL MATERIAL', 'UNIDAD', 'CANTIDAD', 'FECHA DE INGRESO',
       'RESERVA ', 'GUIA DESPACHO', 'OC', 'USO:  OPERCIONES / PROYECTO ',
       'RECIBIDO POR: ', 'UBICACIÓN', 'EMPRESA', 'PRECIO UNITARIO',
       'TOTAL NETO', 'OBSERVACIONES'],
      dtype='object')

In [73]:
ingresos.columns = ingresos.columns.str.strip()
ingresos.columns

Index(['CLASIFICIACIÓN', 'CÓDIGO         SAP/OTRO', 'DESCRIPCIÓN DEL MATERIAL',
       'UNIDAD', 'CANTIDAD', 'FECHA DE INGRESO', 'RESERVA', 'GUIA DESPACHO',
       'OC', 'USO:  OPERCIONES / PROYECTO', 'RECIBIDO POR:', 'UBICACIÓN',
       'EMPRESA', 'PRECIO UNITARIO', 'TOTAL NETO', 'OBSERVACIONES'],
      dtype='object')

In [74]:
ingresos = ingresos.rename(columns={'CÓDIGO         SAP/OTRO': 'CODIGO SAP/OTRO'})
ingresos.columns

Index(['CLASIFICIACIÓN', 'CODIGO SAP/OTRO', 'DESCRIPCIÓN DEL MATERIAL',
       'UNIDAD', 'CANTIDAD', 'FECHA DE INGRESO', 'RESERVA', 'GUIA DESPACHO',
       'OC', 'USO:  OPERCIONES / PROYECTO', 'RECIBIDO POR:', 'UBICACIÓN',
       'EMPRESA', 'PRECIO UNITARIO', 'TOTAL NETO', 'OBSERVACIONES'],
      dtype='object')

## Salidas

In [60]:
salidas = pd.read_excel("data\INSUMOS OPERACIONALES STOCK RELIX.xlsx", sheet_name='SALIDA', skiprows=9)

In [61]:
salidas.head()

,Unnamed: 0,CLASIFICIACIÓN,CÓDIGO SAP / OTRO,DESCRIPCIÓN DEL MATERIAL,UNIDAD,CANTIDAD,FECHA DE SALIDA,N° DE GUÍA DE SALIDAD,USO: OPERACIONES / PROYECTO,ENTREGADO A:,COMENTARIOS,UBICACIÓN DE RETIRO,Unnamed: 12
0,NaN,VALVULAS,11117559,"Válvula Cuchillo 8"" FL (c 150)\nVALVULA CUCHI...",UN,6.0,2025-09-30 00:00:00,NaN,OPERACIONES,RENE MENDOZA,EMPALIZADA,COSAPI,NaN
1,NaN,VALVULAS,22002942,"ESPARRAGO;7/8"" X 1MT LG GRADO 5",UN,12.0,2025-10-09 00:00:00,NaN,OPERACIONES,NELSON AGUILERA,TALLER SOLDADOR,BODEGA RELIX,NaN
2,NaN,VALVULAS,22003670,"ESPARRAGO;7/8"" X 8"" LG GRADO 5",UN,64.0,2025-10-09 00:00:00,NaN,OPERACIONES,ANIBAL ESCOBAR,EMPALIZADA,BODEGA RELIX,NaN
3,NaN,PIPING,11188685,"EMPAQ. FF DN- 10"" # 300 EN BA-U 1/8"" S/ANSI B ...",UN,6.0,2025-10-09 00:00:00,NaN,OPERACIONES,HUGO SALAZAR,EMPALIZADA,BODEGA RELIX,NaN
4,NaN,PIPING,11009709,"EMPAQUETADURA;8"" ANSI 150 8 PERF",UN,10.0,2025-10-10 00:00:00,NaN,OPERACIONES,ERNESTO DIAZ,LINEA PEUMO L3,BODEGA RELIX,NaN

In [62]:
salidas = salidas.drop(salidas.columns[[0, 12]], axis=1)
salidas.head()

,CLASIFICIACIÓN,CÓDIGO SAP / OTRO,DESCRIPCIÓN DEL MATERIAL,UNIDAD,CANTIDAD,FECHA DE SALIDA,N° DE GUÍA DE SALIDAD,USO: OPERACIONES / PROYECTO,ENTREGADO A:,COMENTARIOS,UBICACIÓN DE RETIRO
0,VALVULAS,11117559,"Válvula Cuchillo 8"" FL (c 150)\nVALVULA CUCHI...",UN,6.0,2025-09-30 00:00:00,NaN,OPERACIONES,RENE MENDOZA,EMPALIZADA,COSAPI
1,VALVULAS,22002942,"ESPARRAGO;7/8"" X 1MT LG GRADO 5",UN,12.0,2025-10-09 00:00:00,NaN,OPERACIONES,NELSON AGUILERA,TALLER SOLDADOR,BODEGA RELIX
2,VALVULAS,22003670,"ESPARRAGO;7/8"" X 8"" LG GRADO 5",UN,64.0,2025-10-09 00:00:00,NaN,OPERACIONES,ANIBAL ESCOBAR,EMPALIZADA,BODEGA RELIX
3,PIPING,11188685,"EMPAQ. FF DN- 10"" # 300 EN BA-U 1/8"" S/ANSI B ...",UN,6.0,2025-10-09 00:00:00,NaN,OPERACIONES,HUGO SALAZAR,EMPALIZADA,BODEGA RELIX
4,PIPING,11009709,"EMPAQUETADURA;8"" ANSI 150 8 PERF",UN,10.0,2025-10-10 00:00:00,NaN,OPERACIONES,ERNESTO DIAZ,LINEA PEUMO L3,BODEGA RELIX

In [63]:
salidas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 560 entries, 0 to 559
Data columns (total 11 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   CLASIFICIACIÓN                 341 non-null    object
 1   CÓDIGO         SAP / OTRO      341 non-null    object
 2   DESCRIPCIÓN DEL MATERIAL       341 non-null    object
 3   UNIDAD                         341 non-null    object
 4   CANTIDAD                       341 non-null    float64
 5   FECHA DE SALIDA                341 non-null    object
 6   N° DE GUÍA DE SALIDAD          0 non-null      float64
 7   USO:  OPERACIONES / PROYECTO   341 non-null    object
 8   ENTREGADO  A:                  341 non-null    object
 9   COMENTARIOS                    339 non-null    object
 10  UBICACIÓN DE RETIRO            275 non-null    object
dtypes: float64(2), object(9)
memory usage: 48.2+ KB

In [64]:
salidas['ENTREGADO  A: '].unique()

array(['RENE MENDOZA', 'NELSON AGUILERA', 'ANIBAL ESCOBAR',
       'HUGO SALAZAR', 'ERNESTO DIAZ', 'VICTOR PEREZ ', 'CLAUDIO VERA',
       'MOISES SILVA', 'ALEXANDER PINO', 'VICTOR GACITUA',
       'CAROLINA LAGOS', 'CAMILO MALAVE', 'SEBASTIAN MUÑOZ',
       'VICTO PEREZ', 'ARIEL SALAS', 'CLAUDIO RIVERA', 'NELSON INZUNZA',
       'JOSE SIERRA ', 'RAUL RIVERA', 'JORGE VASQUEZ',
       'IGNACIO VALENZUELA', 'FELIPE ROJAS', 'ALEXANDER CID',
       'CARLOS GOYCOLEA', 'ANDRES VILLALOBOS', 'PAULINA CASTILLO',
       'JOSE LOPEZ', 'FRANCISCO AVELLO', 'SEBASTIAN CORDOBA',
       'LUIS ROBLES', 'ALEJANDRO ROJAS', 'JOSE SIERRA', nan], dtype=object)

In [65]:
salidas = salidas[salidas['CÓDIGO         SAP / OTRO'].isnull()]
salidas

,CLASIFICIACIÓN,CÓDIGO SAP / OTRO,DESCRIPCIÓN DEL MATERIAL,UNIDAD,CANTIDAD,FECHA DE SALIDA,N° DE GUÍA DE SALIDAD,USO: OPERACIONES / PROYECTO,ENTREGADO A:,COMENTARIOS,UBICACIÓN DE RETIRO
341,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
343,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
344,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
557,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
558,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
559,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
salidas = salidas.dropna(subset=['CODIGO         SAP / OTRO'])
salidas

KeyError: ['CODIGO         SAP / OTRO']