# Importación de librerías

In [2]:
import pandas as pd
import sqlite3

# Ingesta de datos

In [3]:
ingresos = pd.read_excel("data\INSUMOS OPERACIONALES STOCK RELIX.xlsx", sheet_name='INGRESO', skiprows=9)

In [4]:
ingresos.head()

,Unnamed: 0,CLASIFICIACIÓN,CÓDIGO SAP/OTRO,DESCRIPCIÓN DEL MATERIAL,UNIDAD,CANTIDAD,FECHA DE INGRESO,RESERVA,GUIA DESPACHO,OC,USO: OPERCIONES / PROYECTO,RECIBIDO POR:,UBICACIÓN,EMPRESA,PRECIO UNITARIO,TOTAL NETO,OBSERVACIONES
0,NaN,VALVULAS,11178702,"Valvula 8""clase 300 (L)\nVÁLVULA;FLSMIDTH;TGHP...",UN,8.0,2025-09-25,5080832,135973,4510237047,EMPALIZADA 23,KAREM GONZALEZ,PATIO EX COSAPIN,FLSMIDTH S.A,11035478.0,88283824.0,NaN
1,NaN,VALVULAS,11117559,"Válvula Cuchillo 8"" FL (c 150)\nVALVULA CUCHI...",UN,20.0,2025-09-25,4947998,135974,4510231212,OPERACIONES,KAREM GONZALEZ,PATIO EX COSAPIN,FLSMIDTH S.A,2783917.0,55678340.0,NaN
2,NaN,IMPERMEABILIAZACIÓN,11019930,GEOMEMBRANA;7.01X210MT 1.5MM ESP HDPE,M2,2944.0,2025-09-28,5152005,151237,4510240486,OPERACIONES,KAREM GONZALEZ,PATIO EX COSAPIN,POLYTEX S.A,2173.0,6397312.0,NaN
3,NaN,IMPERMEABILIAZACIÓN,11019930,GEOMEMBRANA;7.01X210MT 1.5MM ESP HDPE,M2,2944.0,2025-09-28,5152005,151157,4510240486,OPERACIONES,KAREM GONZALEZ,PATIO EX COSAPIN,POLYTEX S.A,2169.0,6385536.0,NaN
4,NaN,IMPERMEABILIAZACIÓN,11019930,GEOMEMBRANA;7.01X210MT 1.5MM ESP HDPE,M2,2944.0,2025-09-28,5152005,151017,4510240486,OPERACIONES,KAREM GONZALEZ,PATIO EX COSAPIN,POLYTEX S.A,2205.0,6491520.0,NaN

### Eliminación columnas innecesarias

In [5]:
ingresos = ingresos.drop(ingresos.columns[0], axis=1)
ingresos.head()

,CLASIFICIACIÓN,CÓDIGO SAP/OTRO,DESCRIPCIÓN DEL MATERIAL,UNIDAD,CANTIDAD,FECHA DE INGRESO,RESERVA,GUIA DESPACHO,OC,USO: OPERCIONES / PROYECTO,RECIBIDO POR:,UBICACIÓN,EMPRESA,PRECIO UNITARIO,TOTAL NETO,OBSERVACIONES
0,VALVULAS,11178702,"Valvula 8""clase 300 (L)\nVÁLVULA;FLSMIDTH;TGHP...",UN,8.0,2025-09-25,5080832,135973,4510237047,EMPALIZADA 23,KAREM GONZALEZ,PATIO EX COSAPIN,FLSMIDTH S.A,11035478.0,88283824.0,NaN
1,VALVULAS,11117559,"Válvula Cuchillo 8"" FL (c 150)\nVALVULA CUCHI...",UN,20.0,2025-09-25,4947998,135974,4510231212,OPERACIONES,KAREM GONZALEZ,PATIO EX COSAPIN,FLSMIDTH S.A,2783917.0,55678340.0,NaN
2,IMPERMEABILIAZACIÓN,11019930,GEOMEMBRANA;7.01X210MT 1.5MM ESP HDPE,M2,2944.0,2025-09-28,5152005,151237,4510240486,OPERACIONES,KAREM GONZALEZ,PATIO EX COSAPIN,POLYTEX S.A,2173.0,6397312.0,NaN
3,IMPERMEABILIAZACIÓN,11019930,GEOMEMBRANA;7.01X210MT 1.5MM ESP HDPE,M2,2944.0,2025-09-28,5152005,151157,4510240486,OPERACIONES,KAREM GONZALEZ,PATIO EX COSAPIN,POLYTEX S.A,2169.0,6385536.0,NaN
4,IMPERMEABILIAZACIÓN,11019930,GEOMEMBRANA;7.01X210MT 1.5MM ESP HDPE,M2,2944.0,2025-09-28,5152005,151017,4510240486,OPERACIONES,KAREM GONZALEZ,PATIO EX COSAPIN,POLYTEX S.A,2205.0,6491520.0,NaN

In [6]:
ingresos.columns

Index(['CLASIFICIACIÓN ', 'CÓDIGO         SAP/OTRO',
       'DESCRIPCIÓN DEL MATERIAL', 'UNIDAD', 'CANTIDAD', 'FECHA DE INGRESO',
       'RESERVA ', 'GUIA DESPACHO', 'OC', 'USO:  OPERCIONES / PROYECTO ',
       'RECIBIDO POR: ', 'UBICACIÓN', 'EMPRESA', 'PRECIO UNITARIO',
       'TOTAL NETO', 'OBSERVACIONES'],
      dtype='object')

In [7]:
ingresos.columns = ingresos.columns.str.strip()
ingresos.columns

Index(['CLASIFICIACIÓN', 'CÓDIGO         SAP/OTRO', 'DESCRIPCIÓN DEL MATERIAL',
       'UNIDAD', 'CANTIDAD', 'FECHA DE INGRESO', 'RESERVA', 'GUIA DESPACHO',
       'OC', 'USO:  OPERCIONES / PROYECTO', 'RECIBIDO POR:', 'UBICACIÓN',
       'EMPRESA', 'PRECIO UNITARIO', 'TOTAL NETO', 'OBSERVACIONES'],
      dtype='object')

In [8]:
ingresos = ingresos.rename(columns={'CÓDIGO         SAP/OTRO': 'CODIGO SAP/OTRO', 'CLASIFICIACIÓN': 'CLASIFICACION'})
ingresos.columns

Index(['CLASIFICACION', 'CODIGO SAP/OTRO', 'DESCRIPCIÓN DEL MATERIAL',
       'UNIDAD', 'CANTIDAD', 'FECHA DE INGRESO', 'RESERVA', 'GUIA DESPACHO',
       'OC', 'USO:  OPERCIONES / PROYECTO', 'RECIBIDO POR:', 'UBICACIÓN',
       'EMPRESA', 'PRECIO UNITARIO', 'TOTAL NETO', 'OBSERVACIONES'],
      dtype='object')