# Importación de librerías

In [2]:
import pandas as pd
import sqlite3

# Ingesta de datos

In [3]:
archivo_excel = pd.ExcelFile("data\INSUMOS OPERACIONALES STOCK RELIX.xlsx")
print("Hojas disponibles:", archivo_excel.sheet_names)

Hojas disponibles: ['Insumos Operacionales 2025', 'INGRESO', 'SALIDA', 'STOCK ']

In [4]:
salidas = pd.read_excel("data\INSUMOS OPERACIONALES STOCK RELIX.xlsx", sheet_name='SALIDA', skiprows=9)

In [5]:
salidas.head()

,Unnamed: 0,CLASIFICIACIÓN,CÓDIGO SAP / OTRO,DESCRIPCIÓN DEL MATERIAL,UNIDAD,CANTIDAD,FECHA DE SALIDA,N° DE GUÍA DE SALIDAD,USO: OPERACIONES / PROYECTO,ENTREGADO A:,COMENTARIOS,UBICACIÓN DE RETIRO,Unnamed: 12
0,NaN,VALVULAS,11117559,"Válvula Cuchillo 8"" FL (c 150)\nVALVULA CUCHI...",UN,6.0,2025-09-30 00:00:00,NaN,OPERACIONES,RENE MENDOZA,EMPALIZADA,COSAPI,NaN
1,NaN,VALVULAS,22002942,"ESPARRAGO;7/8"" X 1MT LG GRADO 5",UN,12.0,2025-10-09 00:00:00,NaN,OPERACIONES,NELSON AGUILERA,TALLER SOLDADOR,BODEGA RELIX,NaN
2,NaN,VALVULAS,22003670,"ESPARRAGO;7/8"" X 8"" LG GRADO 5",UN,64.0,2025-10-09 00:00:00,NaN,OPERACIONES,ANIBAL ESCOBAR,EMPALIZADA,BODEGA RELIX,NaN
3,NaN,PIPING,11188685,"EMPAQ. FF DN- 10"" # 300 EN BA-U 1/8"" S/ANSI B ...",UN,6.0,2025-10-09 00:00:00,NaN,OPERACIONES,HUGO SALAZAR,EMPALIZADA,BODEGA RELIX,NaN
4,NaN,PIPING,11009709,"EMPAQUETADURA;8"" ANSI 150 8 PERF",UN,10.0,2025-10-10 00:00:00,NaN,OPERACIONES,ERNESTO DIAZ,LINEA PEUMO L3,BODEGA RELIX,NaN

### Eliminación columnas innecesarias

In [6]:
salidas = salidas.drop(salidas.columns[[0, 12]], axis=1)
salidas.head()

,CLASIFICIACIÓN,CÓDIGO SAP / OTRO,DESCRIPCIÓN DEL MATERIAL,UNIDAD,CANTIDAD,FECHA DE SALIDA,N° DE GUÍA DE SALIDAD,USO: OPERACIONES / PROYECTO,ENTREGADO A:,COMENTARIOS,UBICACIÓN DE RETIRO
0,VALVULAS,11117559,"Válvula Cuchillo 8"" FL (c 150)\nVALVULA CUCHI...",UN,6.0,2025-09-30 00:00:00,NaN,OPERACIONES,RENE MENDOZA,EMPALIZADA,COSAPI
1,VALVULAS,22002942,"ESPARRAGO;7/8"" X 1MT LG GRADO 5",UN,12.0,2025-10-09 00:00:00,NaN,OPERACIONES,NELSON AGUILERA,TALLER SOLDADOR,BODEGA RELIX
2,VALVULAS,22003670,"ESPARRAGO;7/8"" X 8"" LG GRADO 5",UN,64.0,2025-10-09 00:00:00,NaN,OPERACIONES,ANIBAL ESCOBAR,EMPALIZADA,BODEGA RELIX
3,PIPING,11188685,"EMPAQ. FF DN- 10"" # 300 EN BA-U 1/8"" S/ANSI B ...",UN,6.0,2025-10-09 00:00:00,NaN,OPERACIONES,HUGO SALAZAR,EMPALIZADA,BODEGA RELIX
4,PIPING,11009709,"EMPAQUETADURA;8"" ANSI 150 8 PERF",UN,10.0,2025-10-10 00:00:00,NaN,OPERACIONES,ERNESTO DIAZ,LINEA PEUMO L3,BODEGA RELIX

In [7]:
salidas.columns

Index(['CLASIFICIACIÓN ', 'CÓDIGO         SAP / OTRO',
       'DESCRIPCIÓN DEL MATERIAL', 'UNIDAD', 'CANTIDAD', 'FECHA DE SALIDA',
       'N° DE GUÍA DE SALIDAD', 'USO:  OPERACIONES / PROYECTO ',
       'ENTREGADO  A: ', 'COMENTARIOS', 'UBICACIÓN DE RETIRO'],
      dtype='object')

In [8]:
salidas = salidas.rename(columns={'CLASIFICIACÓN': 'CLASIFICACION', 'CÓDIGO         SAP / OTRO': 'CODIGO SAP/OTRO', 'N° DE GUÍA DE SALIDAD': 'N° DE GUIA DE SALIDA'})
salidas.columns

Index(['CLASIFICIACIÓN ', 'CODIGO SAP/OTRO', 'DESCRIPCIÓN DEL MATERIAL',
       'UNIDAD', 'CANTIDAD', 'FECHA DE SALIDA', 'N° DE GUIA DE SALIDA',
       'USO:  OPERACIONES / PROYECTO ', 'ENTREGADO  A: ', 'COMENTARIOS',
       'UBICACIÓN DE RETIRO'],
      dtype='object')

In [9]:
salidas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 560 entries, 0 to 559
Data columns (total 11 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   CLASIFICIACIÓN                 341 non-null    object
 1   CODIGO SAP/OTRO                341 non-null    object
 2   DESCRIPCIÓN DEL MATERIAL       341 non-null    object
 3   UNIDAD                         341 non-null    object
 4   CANTIDAD                       341 non-null    float64
 5   FECHA DE SALIDA                341 non-null    object
 6   N° DE GUIA DE SALIDA           0 non-null      float64
 7   USO:  OPERACIONES / PROYECTO   341 non-null    object
 8   ENTREGADO  A:                  341 non-null    object
 9   COMENTARIOS                    339 non-null    object
 10  UBICACIÓN DE RETIRO            275 non-null    object
dtypes: float64(2), object(9)
memory usage: 48.2+ KB

### Verificación valores nulos

In [10]:
salidas[salidas['CODIGO SAP/OTRO'].isnull()]

,CLASIFICIACIÓN,CODIGO SAP/OTRO,DESCRIPCIÓN DEL MATERIAL,UNIDAD,CANTIDAD,FECHA DE SALIDA,N° DE GUIA DE SALIDA,USO: OPERACIONES / PROYECTO,ENTREGADO A:,COMENTARIOS,UBICACIÓN DE RETIRO
341,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
343,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
344,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
557,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
558,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
559,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
salidas = salidas.dropna(subset=['CODIGO SAP/OTRO'])
salidas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 341 entries, 0 to 340
Data columns (total 11 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   CLASIFICIACIÓN                 341 non-null    object
 1   CODIGO SAP/OTRO                341 non-null    object
 2   DESCRIPCIÓN DEL MATERIAL       341 non-null    object
 3   UNIDAD                         341 non-null    object
 4   CANTIDAD                       341 non-null    float64
 5   FECHA DE SALIDA                341 non-null    object
 6   N° DE GUIA DE SALIDA           0 non-null      float64
 7   USO:  OPERACIONES / PROYECTO   341 non-null    object
 8   ENTREGADO  A:                  341 non-null    object
 9   COMENTARIOS                    339 non-null    object
 10  UBICACIÓN DE RETIRO            275 non-null    object
dtypes: float64(2), object(9)
memory usage: 32.0+ KB